death-cost:
  target-account:
  use-simple-mode: false
  simple-mode:
    if-percent: false
    cost: 50.0
  complex-mode:
    - max: 5000.0
      cost: 0.0
      if-percent: false
    - max: 10000.0
      cost: 20.0
      if-percent: false
    - max: 50000.0
      cost: 0.001
      if-percent: true
    - max: -1.0
      cost: 0.0024
      if-percent: true
death-message:
  player-enable: true
  broadcast-enable: false
  console-enable: false