world-size:
  world:
    x1: -10000
    z1: -10000
    x2: +10000
    z2: +10000
waiting-second: 5
start-warning-sound: BLOCK_NOTE_BLOCK_BIT
start-warning-second: 3
start-speed: 1.0
arrive-music:
  - 0 F3 BLOCK_NOTE_BLOCK_PLING 5
  - 6 C♯3 BLOCK_NOTE_BLOCK_PLING 5
  - 12 D♯3 BLOCK_NOTE_BLOCK_PLING 5
  - 18 G♯2 BLOCK_NOTE_BLOCK_PLING 5
start-music:
  - 0 C♯3 BLOCK_NOTE_BLOCK_PLING 5
  - 6 F3 BLOCK_NOTE_BLOCK_PLING 5
  - 12 G♯3 BLOCK_NOTE_BLOCK_PLING 5
  - 18 C♯4 BLOCK_NOTE_BLOCK_PLING 5
