rootProject.name = "NewNanPlugins"
include(":RailArea")
include(":BetterBook")
include(":RailExpress")
include(":FeeFly")
include(":DeathCost")
include(":MCron")
include(":MCPatch")
include(":Guardian")
include(":Foundation")
include(":TPA")
include(":BetterCommandBlock")
include(":CreateArea")
include(":PowerTools")
include(":NewNanMain")