name: ${project.name}
version: ${project.version}
main: io.github.gk0wk.railexpress.RailExpress
authors: [ Gk0Wk ]
api-version: 1.16
load: STARTUP
description: ${projectdescription}
website: https://gk0wk.github.io/
