name: ${project.name}
version: ${project.version}
main: ${project.group}.PluginMain
api-version: ${project.apiVersion}
load: ${project.load}
authors: ${project.authors}
description: ${project.description}
website: ${project.url}
# 硬依赖，没有就无法启动
depend: ${project.depend}
loadbefore: ${project.loadBefore}
softdepend: ${project.softDepend}

# 权限节点，可选
permissions:
  # 模板
  # 'Example':
  #  description: '权限的解释'
  #  default: 玩家权限节点的默认值，true、false、op和not op
  #  children: #子节点(仅名字)
  #    'Example2': true会继承父节点的权限，false会与父节点相反
  'betterbook.bypass':
    description: '略过检查权限'
    default: op