blocked-commands:
  - op
  - minecraft:op
  - deop
  - minecraft:deop
  - ban
  - minecraft:ban
  - banlist
  - minecraft:banlist
  - ban-ip
  - minecraft:ban-ip
  - pardon
  - minecraft:pardon
  - pardon-ip
  - minecraft:pardon-ip
  - whitelist
  - minecraft:whitelist
  - kick
  - minecraft:kick
  - stop
  - minecraft:stop
  - save-all
  - minecraft:save-all
  - save-off
  - minecraft:save-off
  - save-on
  - minecraft:save-on
  - minecraft:reload
  - debug
  - minecraft:debug
  - testfor
  - minecraft:testfor
  - defaultgamemode
  - minecraft:defaultgamemode
  - seed
  - minecraft:seed
  - datapack
  - minecraft:datapack
  - data
  - minecraft:data
  - publish
  - minecraft:publish
  - timimgs
  - bukkit:timings
  - plugins
  - bukkit:plugins
  - pl
  - bukkit:pl
  - reload
  - bukkit:reload
  - rl
  - bukkit:rl
  - bukkit:timings
  - ver
  - version
  - bukkit:ver
  - bukkit:version