name: ${project.name}
version: ${project.version}
main: ${project.group}.PluginMain
api-version: ${project.apiVersion}
load: ${project.load}
authors: ${project.authors}
description: ${project.description}
website: ${project.url}
# 硬依赖，没有就无法启动
depend: ${project.depend}
loadbefore: ${project.loadBefore}
softdepend: ${project.softDepend}

permissions:
  'guardian.bypass':
    description: '略过检查权限'
    default: op